name: Aspect-Based-Sentiment-Analysis
dependencies:
  - python=3.6.9
  - scikit-learn
  - pytest
  - pytest-timeout
  - ipython=7.3
  - spacy>3
  - dataclasses
  - pip:
      - tensorflow==2.2
      - google-cloud-storage==1.26
      - testfixtures
      - transformers
      - optuna
