name: Aspect-Based-Sentiment-Analysis
dependencies:
  - python=3.6.9
  - scikit-learn=0.22
  - pytest=5.3
  - pytest-timeout=1.3
  - ipython=7.3
  - spacy
  - dataclasses=0.7
  - pip:
      - tensorflow==2.2
      - google-cloud-storage==1.26
      - testfixtures==6.14
      - transformers
      - optuna==1.3
